In [0]:
from google.colab import files
files.upload()

In [10]:
!ls -lha kaggle.json

-rw-r--r-- 1 root root 63 Nov 16 07:26 kaggle.json


In [0]:
!pip install -q kaggle

In [0]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [0]:
!chmod 600 ~/.kaggle/kaggle.json

In [14]:
!kaggle competitions download -c digit-recognizer

# https://stackoverflow.com/questions/49310470/using-kaggle-datasets-into-google-colab

 97% 71.0M/73.2M [00:00<00:00, 93.3MB/s]
100% 73.2M/73.2M [00:00<00:00, 177MB/s] 
 55% 27.0M/48.8M [00:00<00:00, 63.3MB/s]
100% 48.8M/48.8M [00:00<00:00, 166MB/s] 
  0% 0.00/235k [00:00<?, ?B/s]
100% 235k/235k [00:00<00:00, 141MB/s]


In [0]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils

In [16]:
train_dataset = np.loadtxt('train.csv', skiprows=1, dtype='int', delimiter=',')
print(train_dataset)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [0]:
x_train = train_dataset[:, 1:]

x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)

x_train = x_train.astype("float32")
x_train /= 255.0

In [0]:
y_train = train_dataset[:, 0]

y_train = np_utils.to_categorical(y_train)

In [19]:
model = Sequential()

model.add(Conv2D(75, kernel_size=(5, 5),activation='elu',input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Conv2D(100, (5, 5), activation='elu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(500, activation='elu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))


model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
print(model.summary())

model.fit(x_train, y_train, batch_size=400, epochs=10, verbose=2)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 24, 24, 75)        1950      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 75)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 75)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 8, 100)         187600    
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 4, 100)         0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 4, 4, 100)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1600)              0         
__________

In [20]:

model = Sequential()

model.add(Conv2D(75, kernel_size=(5, 5),activation='relu',input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Conv2D(100, (5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(500, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(300, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))


model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
print(model.summary())

model.fit(x_train, y_train, batch_size=100, epochs=15, verbose=2)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 24, 24, 75)        1950      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 12, 12, 75)        0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 12, 12, 75)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 8, 8, 100)         187600    
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 4, 4, 100)         0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 4, 4, 100)         0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 1600)              0         
__________

In [33]:

model = Sequential()

model.add(Conv2D(75, kernel_size=(5, 5),activation='relu',input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Conv2D(100, (5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(300, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(100, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))


model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
print(model.summary())

model.fit(x_train, y_train, batch_size=100, epochs=15, verbose=2)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_23 (Conv2D)           (None, 24, 24, 75)        1950      
_________________________________________________________________
max_pooling2d_21 (MaxPooling (None, 12, 12, 75)        0         
_________________________________________________________________
dropout_42 (Dropout)         (None, 12, 12, 75)        0         
_________________________________________________________________
conv2d_24 (Conv2D)           (None, 8, 8, 100)         187600    
_________________________________________________________________
max_pooling2d_22 (MaxPooling (None, 4, 4, 100)         0         
_________________________________________________________________
dropout_43 (Dropout)         (None, 4, 4, 100)         0         
_________________________________________________________________
flatten_9 (Flatten)          (None, 1600)              0         
__________

In [0]:

test_dataset = np.loadtxt('test.csv', skiprows=1, delimiter=",")

x_test = test_dataset.reshape(test_dataset.shape[0], 28, 28, 1)
x_test /= 255.0

In [0]:
predictions = model.predict(x_test)

predictions = np.argmax(predictions, axis=1)

In [0]:
out = np.column_stack((range(1, predictions.shape[0]+1), predictions))
np.savetxt('submission.csv', out, header="ImageId,Label", 
            comments="", fmt="%d,%d")

In [0]:
files.download('submission.csv')